### ISSUE TITLE
[docker] kafka

### ISSUE THREAD

**Issue by Alice52** [Alice52/mq-tutorial#3]
```yml
version: '2'
services:
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:7.4.5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:7.4.5
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://101.34.6.110:9092,PLAINTEXT_HOST://101.34.6.110:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  kafka-map:
    hostname: kafka-map
    image: dushixiang/kafka-map:latest
    ports:
      - "9009:8080"
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin
    depends_on:
      - kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.5
    container_name: schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
```
